<template>
  <div id="file-explorer" class="wrapper" :class="showAnimation ? 'wrapper bgimg fade-in' : ''">
    <div v-if="showAnimation" class="fileList">
      <FileItem v-for="(item, index) in projects" :name="item.name" :icon="asset_prefix + item.icon" :key="index"
        :link="item.link" />
    </div>

  </div>
</template>

<script setup lang="ts">
import FileItem from './FileItem.vue';
import { usePageFrontmatter, useSiteData } from "@vuepress/client";
import { ref } from 'vue';

const frontmatter = usePageFrontmatter();
const siteData = useSiteData()
const asset_prefix = siteData.value.base

const projects = frontmatter.value.projects;

const showAnimation = ref(false)

const active = () => {
  if (!showAnimation.value) {
    showAnimation.value = true
  }
}

defineExpose({ active })


// todo : 点击文件夹，背景图向下移动后再执行路由跳转

</script>

<style scoped>
.wrapper {
  height: 100vh;
  width: 100%;
}

.bgimg {
  background-image: url('/w11-h.jpg');
  background-size: cover;
}

.fileList {
  display: flex;
  padding: 20px;
  flex-wrap: wrap;
}

.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-9 0:35:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
</style>