<template>
    <div class="dir scale-up-center" @click="()=>router.push(link)">
        <div class= "content">
            <img :src="icon" alt="">
            <div class="dec tracking-in-expand">{{ name }}</div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from "vue-router";
const router = useRouter()

interface IProps {
    name: string
    icon: string,
    link: string,
}

const { name, icon, link } = defineProps<IProps>()


</script>

<style  scoped>
.dir {
    width: 140px;
    height: 140px;
    padding: 10px;
    display: flex;
    margin : 30px;
    align-items: center;
    position: relative;
    justify-content: center;
}


.dir:hover{
    background-color: rgb(157, 193, 216);
}

.content{
   position: absolute; 
}

img {
    width: 120px;
    height: 120px;
}

.dec {
    user-select:none;
    text-align: center;
    font-size: 1.5rem;
}



.scale-up-center {
	animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.7s both;
}

.tracking-in-expand {
	animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000)1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-8 23:52:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
 @keyframes scale-up-center {
  0% {
    transform: scale(0);
  }
  100% {
    transform: scale(1);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-8 23:59:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
 @keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}



</style>