<template>
  <div id="file-explorer" class="wrapper bgimg" :class="animationClass">
    <div v-if="viewIn" class="fileList">
      <FileItem v-for="(item, index) in projects" :name="item.name" :icon="asset_prefix + item.icon" :key="index"
        :link="item.link" :onLeave="onLeave" />
    </div>

  </div>
</template>

<script setup lang="ts">
import FileItem from './FileItem.vue';
import { usePageFrontmatter, useSiteData } from "@vuepress/client";
import { ref, computed } from 'vue';


const frontmatter = usePageFrontmatter();
const siteData = useSiteData()
const asset_prefix = siteData.value.base

const projects = frontmatter.value.projects;

const viewIn = ref<boolean | null>(null)

const animationClass = computed(() => {
  if (viewIn.value === undefined) {
    return ''
  } else if (viewIn.value === true) {
    return 'fade-in'
  } else if (viewIn.value === false) {
    return 'puff-out-center'
  }
})

const active = () => {
  if (viewIn.value === null) {
    viewIn.value = true
  }
}

defineExpose({ active })


const onLeave = () => {
  if (viewIn.value === true) {
    viewIn.value = false
  }
}

</script>

<style scoped>
.wrapper {
  height: 100vh;
  width: 100%;
  /* overflow: hidden; */
}

.bgimg {
  background-image: url('/w11-h.jpg');
  background-size: cover;
}

.fileList {
  display: flex;
  padding: 20px;
  flex-wrap: wrap;
}

.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}


.puff-out-center {
  -webkit-animation: puff-out-center 1s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
  animation: puff-out-center 1s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
}


/* ----------------------------------------------
 * Generated by Animista on 2023-4-9 0:35:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}


/* ----------------------------------------------
 * Generated by Animista on 2023-4-12 9:48:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation puff-out-center
 * ----------------------------------------
 */
@-webkit-keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }

  100% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-filter: blur(4px);
    filter: blur(4px);
    opacity: 0;
  }
}

@keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }

  100% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-filter: blur(4px);
    filter: blur(4px);
    opacity: 0;
  }
}
</style>