<template>
  <div id="file-explorer" class="wrapper bgimg" :class="animationClass">
    <div v-if="viewIn" class="fileList">
      <FileItem v-for="(item, index) in projects" :name="item.name" :icon="item.icon" :key="index"
        :link="item.link" />
    </div>

  </div>
</template>

<script setup lang="ts">
import FileItem from './FileItem.vue';
import { ref, computed } from 'vue';

interface IProps {
  frontmatter: any
}

const { frontmatter } = defineProps<IProps>()

const projects = frontmatter.projects;

const viewIn = ref<boolean | null>(null)

const animationClass = computed(() => {
  return viewIn.value ? 'fade-in' : ''
})

const active = () => {
  if (viewIn.value === null) {
    viewIn.value = true
  }
}

defineExpose({ active })


</script>

<style scoped>
.wrapper {
  height: 100vh;
  width: 100%;
}

.bgimg {
  background-image: url('/w11-h-60.jpg');
  background-size: cover;
}

.fileList {
  display: flex;
  margin: 20px;
  flex-wrap: wrap;
}

.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}


/* ----------------------------------------------
 * Generated by Animista on 2023-4-9 0:35:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}



</style>