<template>
    <div v-if="showView" class="wrapper bg-pan-left bg-color" >
        <div class="content-wrapper flex-box tilt-in-fwd-tr">
            <div class="content">
                <div class="avater"><img :src=" avatar" alt=""></div>
                <div class="name">{{ title }}</div>
                <div class="describe">{{ description }}</div>
                <div class="link">
                    <a :href="github" target="_blank"><img src="/github.svg" alt=""></a>
                    <a :href="mail" target="_blank"><img src="/mail.svg" alt=""></a>
                    <a :href="music" target="_blank"><img src="/music.svg" alt=""></a>
                </div>
                <div class="flex-box">
                    <div @click="showMe" class="btn">让我康康！</div>
                </div>
            </div>
        </div>
    </div>
    <!-- <img @click="showMe" src="/down.svg" class="down-icon" alt=""> -->
</template>

<script setup lang="ts">
import { activeFileExplorer } from '../const'
import { SiteData } from '@vuepress/client';
import { useRouter } from "vue-router";
import { ref } from 'vue'

interface IProps {
    siteData: SiteData,
    frontmatter: any
}

const { siteData, frontmatter } = defineProps<IProps>()
const showView = ref(true)


const title = siteData.title
const description = siteData.description
const avatar = frontmatter.avatar;
const music = frontmatter.music;
const github = frontmatter.github;
const mail = frontmatter.mail;

const router = useRouter()
const emit = defineEmits([activeFileExplorer]);

const showMe = () => {
    router.push('#file-explorer')
    emit(activeFileExplorer)
    setTimeout(() => {
        showView.value = false
    }, 1000)
}


</script>

<style lang="scss" scoped>
.wrapper {
    height: 100vh;
    width: 100%;
    overflow: hidden;
    top: 0;
    left: 0;
    position: absolute;
}

.flex-box {
    display: flex;
    align-items: center;
    justify-content: center;
}

.bg-color {
    // background: linear-gradient(to right, #29EAC4, #4284DB);
    background-image: linear-gradient(270deg, #cc6aa5, #3e91cc, #2dcca7);
    background-size: 600% 100%;
}
.content-wrapper {
    height: 100%;
    width: 100%;
}

.content {
    width: 300px;
    height: 300px;

    .avater {
        display: flex;
        align-items: center;
        justify-content: center;

        img {
            width: 60%;
            height: 60%;
            border-radius: 50%;
        }
    }

    .name {
        font-size: 30px;
        // color: white;
        text-align: center;
        margin-top: 10px;
    }

    .describe {
        font-size: 20px;
        // color: white;
        text-align: center;
        margin-top: 10px;
        font-style: italic;
    }
}

.link{
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 10px;

    a {
        margin: 0 10px;
        img {
            width: 30px;
            height: 30px;
        }
    }
}

.tilt-in-fwd-tr {
	animation: tilt-in-fwd-tr 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0.5s both;
}

.bg-pan-left {
    animation: bg-pan-left 8s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-9 10:11:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bg-pan-left
 * ----------------------------------------
 */


@keyframes bg-pan-left {
    0% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-12 15:38:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-fwd-tr
 * ----------------------------------------
 */
 @keyframes tilt-in-fwd-tr {
  0% {
    transform: rotateY(20deg) rotateX(35deg) translate(300px, -300px) skew(-35deg, 10deg);
    opacity: 0;
  }
  100% {
    transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    opacity: 1;
  }
}



.btn {
    margin-top: 20px;
    user-select: none;
    position: relative;
    padding: 10px 20px;
    border-radius: 7px;
    // border: 1px solid rgb(61, 106, 255);
    font-size: 20px;
    text-transform: uppercase;
    font-weight: 600;
    letter-spacing: 2px;
    background: transparent;
    color: #fff;
    overflow: hidden;
    box-shadow: 0 0 0 0 transparent;
    -webkit-transition: all 0.2s ease-in;
    -moz-transition: all 0.2s ease-in;
    transition: all 0.2s ease-in;
}

.btn:hover {
    background: rgb(61, 106, 255);
    box-shadow: 0 0 30px 5px rgba(0, 142, 236, 0.815);
    -webkit-transition: all 0.2s ease-out;
    -moz-transition: all 0.2s ease-out;
    transition: all 0.2s ease-out;
}

.btn:hover::before {
    -webkit-animation: sh02 0.5s 0s linear;
    -moz-animation: sh02 0.5s 0s linear;
    animation: sh02 0.5s 0s linear;
}

.btn::before {
    content: '';
    display: block;
    width: 0px;
    height: 86%;
    position: absolute;
    top: 7%;
    left: 0%;
    opacity: 0;
    background: #fff;
    box-shadow: 0 0 50px 30px #fff;
    -webkit-transform: skewX(-20deg);
    -moz-transform: skewX(-20deg);
    -ms-transform: skewX(-20deg);
    -o-transform: skewX(-20deg);
    transform: skewX(-20deg);
}

@keyframes sh02 {
    from {
        opacity: 0;
        left: 0%;
    }

    50% {
        opacity: 1;
    }

    to {
        opacity: 0;
        left: 100%;
    }
}

.btn:active {
    box-shadow: 0 0 0 0 transparent;
    -webkit-transition: box-shadow 0.2s ease-in;
    -moz-transition: box-shadow 0.2s ease-in;
    transition: box-shadow 0.2s ease-in;
}
</style>