<template>
    <div class="wrapper bg-color bg-pan-left">

    </div>
    <img @click="moveDown" src="/down.svg" class="down-icon" alt="">
</template>

<script setup lang="ts">
import { activeFileExplorer } from '../const'
import { useRoute, useRouter } from "vue-router";

const router = useRouter()

const moveDown = () => {
    // 获取屏幕高度
    // const screenHeight = window.innerHeight;

    // window.scrollTo({
    //     top: screenHeight,
    //     behavior: "smooth",
    // });
    
    router.push('#file-explorer')
    emit(activeFileExplorer)
}

const emit = defineEmits([activeFileExplorer]);


</script>

<style scoped>
.wrapper {
    height: 100vh;
    width: 100%;
}

.bg-color {
    background: #4284DB;
    /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, #29EAC4, #4284DB);
    /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, #29EAC4, #4284DB);
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

}

.bg-pan-left {
    -webkit-animation: bg-pan-left 8s both;
    animation: bg-pan-left 8s both;
}

.down-icon {
    position: absolute;
    bottom: 0;
    left: calc(50vw - 30px);

    width: 60px;
    height: 60px;
    padding: 10px;
    cursor: pointer;

    animation-name: bounce-down;
    animation-duration: 1.5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-9 10:11:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bg-pan-left
 * ----------------------------------------
 */

@keyframes bounce-down {
    from {
        transform: translateY(-5px);
    }

    to {
        transform: translateY(5px);
    }
}

@-webkit-keyframes bg-pan-left {
    0% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }
}

@keyframes bg-pan-left {
    0% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }
}
</style>